In [13]:
import datetime as dt
import pandas as pd
import scipy as s
import numpy as np
import names

In [115]:
numIter = 5 # MANUALLY SELECT: If you choose 5, you will have the randomly selected 10 from article 1, 10 from article 2, etc... 
            # so 51 total articles

randArticleNum = 10 # how many random articles to select from each article 

totArticles = numIter*randArticleNum + 1  # total articles will be the 5 original articles * 10 randomly selected from that article

iterArticles = range(0,totArticles) # create range of articles for for loop later

iterArticles[2] # check to see if range worked

2

In [116]:
# create dataframe with # columns include: authors, article title, DOI, and number of article
                        # rows include:    total number of articles 

# for authors, i used a random name generator because it was kind of fun & holds the place for string values later.
# for title, I simply labeled title 1, 2, etc. to be a filler for actual article titles later.
# I simply labeled DOI with what it's respective value will be as well.
# Number is labeled as #.# where the first number will indicate what article the citation is coming from. 
# For example, 0.1 would indicate the original article (0) and the 1st random article (1)

article = pd.DataFrame({"authors": [names.get_full_name()],"title": ["title %d" % (iterArticles[0])], \
                        "DOI": ["DOI%d" % (iterArticles[0])], 'number': [np.nan]})

# print to make sure we did everything right
print(article)

    DOI        authors  number    title
0  DOI0  Micheal Brown     NaN  title 0

In [117]:
for x in range(1,totArticles):
    print("x = ", x)
    articleAppend = pd.DataFrame({"authors": [names.get_full_name()],"title": ["title %d" % (iterArticles[x])], \
                 "DOI": ["DOI%d" % (iterArticles[x])], 'number': [np.nan]})
    article = article.append(articleAppend, ignore_index = True)

x =  1
x =  2
x =  3
x =  4
x =  5
x =  6
x =  7
x =  8
x =  9
x =  10
x =  11
x =  12
x =  13
x =  14
x =  15
x =  16
x =  17
x =  18
x =  19
x =  20
x =  21
x =  22
x =  23
x =  24
x =  25
x =  26
x =  27
x =  28
x =  29
x =  30
x =  31
x =  32
x =  33
x =  34
x =  35
x =  36
x =  37
x =  38
x =  39
x =  40
x =  41
x =  42
x =  43
x =  44
x =  45
x =  46
x =  47
x =  48
x =  49
x =  50

In [128]:
# now let's assign numbers to each article. 
# Note that article 0.0 = original article, 0.1 = 1st reference from original article
article['number'] = np.arange(0.0,5.1,0.1)
article

      DOI             authors  number     title
0    DOI0       Micheal Brown     0.0   title 0
1    DOI1          John Cohen     0.1   title 1
2    DOI2      Brendon Conrad     0.2   title 2
3    DOI3        Vickie Doran     0.3   title 3
4    DOI4     Veronica Miller     0.4   title 4
5    DOI5       Stephen Evans     0.5   title 5
6    DOI6         Larry Raven     0.6   title 6
7    DOI7     Marvin Kluemper     0.7   title 7
8    DOI8  Sharron Richardson     0.8   title 8
9    DOI9    William Tremblay     0.9   title 9
10  DOI10       Hector Pushaw     1.0  title 10
11  DOI11      Ronald Boggess     1.1  title 11
12  DOI12        Connie Ayers     1.2  title 12
13  DOI13        Thomas Ellis     1.3  title 13
14  DOI14        Sheila Miles     1.4  title 14
15  DOI15        Janet Geiger     1.5  title 15
16  DOI16     Julio Henderson     1.6  title 16
17  DOI17  Christopher Guerra     1.7  title 17
18  DOI18          Billy Reed     1.8  title 18
19  DOI19      Harvey Parrish     1.9  title 19
20  DOI20         Evelyn Reed     2.0  title 20
21  DOI21       Nicole Horton     2.1  title 21
22  DOI22        Michael Dunn     2.2  title 22
23  DOI23    Caroline Ramirez     2.3  title 23
24  DOI24   Elizabeth Collins     2.4  title 24
25  DOI25   Patricia Mccallum     2.5  title 25
26  DOI26     Virginia Bowman     2.6  title 26
27  DOI27       Carol Sanchez     2.7  title 27
28  DOI28     Richard Grisham     2.8  title 28
29  DOI29       Diana Lavigne     2.9  title 29
30  DOI30         Jodi Glasby     3.0  title 30
31  DOI31     Lawrence Aranda     3.1  title 31
32  DOI32         Cheryl Cook     3.2  title 32
33  DOI33        Martin Brown     3.3  title 33
34  DOI34        Larry Lebeau     3.4  title 34
35  DOI35          Mitch Gray     3.5  title 35
36  DOI36      Mario Yasutomi     3.6  title 36
37  DOI37   Sandra Vanderburg     3.7  title 37
38  DOI38         Bobby Helmy     3.8  title 38
39  DOI39           John Cook     3.9  title 39
40  DOI40       Louis Pickens     4.0  title 40
41  DOI41        Ann Pychardo     4.1  title 41
42  DOI42      Eileen Toliver     4.2  title 42
43  DOI43          Karen Reid     4.3  title 43
44  DOI44       Bobby Stewart     4.4  title 44
45  DOI45          Harold Moe     4.5  title 45
46  DOI46   Sharon Iannaccone     4.6  title 46
47  DOI47         Mary Barnes     4.7  title 47
48  DOI48         Diane Jones     4.8  title 48
49  DOI49      Melvin Thurman     4.9  title 49
50  DOI50         Wendy Aaron     5.0  title 50

In [131]:
article.to_csv('data4fig_setup.csv') # export as .csv

51